name: Storybook Visual Regression

on:
  pull_request:
    branches:
      - main

jobs:
  storybook_regression:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Storybook
      run: npm run build-storybook

    - name: Run visual regression tests
      run: npm test -- storyshots.test.js
